#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate the desktop candidate projection's sets from native parser sources."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
engine = (root / "engine/src/phrase_engine.cpp").read_text()
snapshot = (root / "librime-yunpin/src/snapshot_store.cpp").read_text()
standard_match = re.search(r'kSyllables\s*=\s*R"\((.*?)\)"', engine, re.S)
legacy_match = re.search(r'kLegacyPrivateSpellings\s*=\s*\{(.*?)\};', snapshot, re.S)
if standard_match is None or legacy_match is None:
    raise SystemExit("Native syllable declarations changed; inspect parser contract before regenerating")
standard = sorted(set(standard_match.group(1).split()))
legacy = sorted(set(re.findall(r'"([a-z]+)"', legacy_match.group(1))))
if not standard or not legacy or any(not re.fullmatch("[a-z]+", token) for token in standard):
    raise SystemExit("Invalid native syllable declaration")
output = """// SPDX-License-Identifier: Apache-2.0
// Code generated by scripts/generate_snapshot_syllables.py; DO NOT EDIT.
// Authoritative sources: engine/src/phrase_engine.cpp and
// librime-yunpin/src/snapshot_store.cpp. Tests verify these sets remain aligned.
package desktopagent

"""
for name, values in [("nativeSnapshotSyllablesText", standard), ("nativeSnapshotLegacySyllablesText", legacy)]:
    lines = [" ".join(values[index:index + 16]) for index in range(0, len(values), 16)]
    output += "const " + name + " = `\n" + "\n".join(lines) + "\n`\n\n"
(root / "desktopagent/snapshot_syllables_generated.go").write_text(output.rstrip() + "\n")
